steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/theta-grid-399223/secret-keeper', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
      - '-c'
      - |
        gcloud container clusters get-credentials secert-keeper \
          --region us-central1-c

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/deployment.yaml']

images:
- 'gcr.io/theta-grid-399223/secret-keeper'

serviceAccount: secret-keeper-docker-image-ser@theta-grid-399223.iam.gserviceaccount.com  # Replace with your service account email

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
